### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by KeithIMyers** [Prajithp/letsencrypt-cpanel#10]
Good Afternoon,
Upon installing this plugin, I see the option under the WHM plugin manager for "Letsencrypt" however I get a 500 server error after selecting it. Any advice?

Internal Server Error

500

No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 255 when it ended.

**Comment by Prajithp** [comment]
Could you please run this script from command line and paste the result here? so that I can assist you further on this.

```
/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl
```

**Comment by KeithIMyers** [comment]
root@srv1 [~]# /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl
Status: 400 Bad request
Content-Type: application/text; charset=ISO-8859-1

**Comment by Prajithp** [comment]
this looks fine, could you please access whm=>letsencrypt and share the cpanel error log file? so that I can check and assist you.

**Comment by KeithIMyers** [comment]
Here you go

malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "<!DOCTYPE html>\n<ht...") at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 171.
[2016-02-18 10:18:33 -0500] info [cpsrvd] Internal Server Error: "GET /cpsessXXXXXXXXXXXX/cgi/letsencrypt/letsencrypt.pl HTTP/1.1" 500 No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 255 when it ended.

(Removed the Session Token)

**Comment by dochardi** [comment]
Hello I have the same issus that are what the cpanel error log say

CDB_File could not be loaded. You may see pages in English rather than in your desired locale at /usr/local/cpanel/Cpanel/Locale/Utils.pm line 11.
Can't use an undefined value as an ARRAY reference at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 128.
[2016-02-26 23:07:10 +0100] info [cpsrvd] Internal Server Error: "GET /cpsess******/cgi/letsencrypt/letsencrypt.pl HTTP/1.1" 500 No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 2 when it ended.

**Comment by dochardi** [comment]
Hello,

Any infos about how to fix that issus?

**Comment by ashworthconsulting** [comment]
Just got the error, actually. Most of our servers are CentOS 6 or 7, but I just tried on CentOS 5 and that produced the 500 error. Here are details. Log to follow shortly to your email @Prajithp 

```
Internal Server Error

500

No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 2 when it ended.
cpsrvd/11.54.0.17 Server at ___________
```

**Comment by ashworthconsulting** [comment]
```
# /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl
Status: 400 Bad request
Content-Type: application/text; charset=ISO-8859-1

Access denied
```

**Comment by ashworthconsulting** [comment]
I should note, however, that SNI isn't available on CentOS 5. At least I believe that's still the case.

So maybe this is futile on this server.

**Comment by Prajithp** [comment]
@KeithIMyers @ashworthconsulting @dochardi , Could you please upgrade to latest release and see how it works? both mentioned issues has been fixed.

**Comment by ashworthconsulting** [comment]
@Prajithp For me, at least...on CentOS 5 it wouldn't matter, right? Because I'd need to assign each SSL domain to a static IP address. I don't think SNI is on v5, and if it is not, I think I'd be a tad out of luck on that particular server (with no way to upgrade to v6 for that matter...the sites need to be migrated).

**Comment by Prajithp** [comment]
Yes CentOS 5 doesn't support SNI. But, if you have domains with dedicated ip, you can still assign letsencrypt ssl certificate using this.

**Comment by dochardi** [comment]
We can confirme that the laste update fix the 500 error

**Comment by KeithIMyers** [comment]
In my case, the latest update did not fix it for me (CentOS 6.7)

On Mon, Mar 7, 2016 at 12:22 PM, Kai notifications@github.com wrote:

> We can confirme that the laste update fix the 500 error
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Prajithp/letsencrypt-cpanel/issues/10#issuecomment-193357196
> .

## 

[image: --]
Keith I Myers
[image: http://]http://KMyers.me
+Keith I Myers http://plus.kmyers.me/
Mobile : (305)-929-3475

**Comment by Prajithp** [comment]
@KeithIMyers Could you please share the cpanel error log with me?

**Comment by HoustonDad** [comment]
Just installed this on my personal system, getting 500 ISE as well.

```
Internal Server Error
500
No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 255 when it ended.
```

error_log:

```
Server Error from 127.0.0.1: HTTP/1.1 403 Forbidden Access denied
Server Error from 127.0.0.1: HTTP/1.1 403 Forbidden Access denied
[2016-03-08 08:51:38 -0600] info [cpsrvd] Internal Server Error: "GET /cpsess6043162791/cgi/letsencrypt/letsencrypt.pl HTTP/1.1" 500 No response from subprocess (/u
sr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 255 when it ended.
```

```
[pid 30086] 08:52:28 write(3, "POST /json-api/fetch_ssl_vhosts HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: Close\r\nContent-Length: 13\r\nUser-Agent: cPanel::PublicA
PI (perl) 2\r\nAuthorization: WHM root:#{ACCESS_HASH_REMOVED}\r\n\r\napi.version=1", 1139) = 1139 <0.000065>
[pid 30086] 08:52:28 read(3, "HTTP/1.1 403 Forbidden Access denied\r\nConnection: close\r\nContent-type: text/plain; charset=\"utf-8\"\r\n\r\n{\"cpanelresult\":{\"a
piversion\":\"2\",\"error\":\"Access denied\",\"data\":{\"reason\":\"Access denied\",\"result\":\"0\"},\"type\":\"text\"}}\r\n", 4096) = 224 <0.008877>
[pid 30086] 08:52:28 fstat(3, {st_dev=makedev(0, 6), st_ino=72842154, st_mode=S_IFSOCK|0777, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=0, st_size=0
, st_atime=0, st_mtime=0, st_ctime=0}) = 0 <0.000024>
[pid 30086] 08:52:28 read(3, "", 4096)  = 0 <0.000016>
[pid 30086] 08:52:28 write(2, "Server Error from 127.0.0.1: HTTP/1.1 403 Forbidden Access denied\r\n\n", 68) = 68 <0.000047>
```

**Comment by Prajithp** [comment]
Seems, you have enabled some security settings in WHM as I can see the key based auth was denied by WHM. Please check your security settings and let us know.

**Comment by HoustonDad** [comment]
Yep, verified that having 2FA enabled for root causes this to fail.

**Comment by KeithIMyers** [comment]
This does make sense as I also have 2FA turned on for my root account. 

@Prajithp - do you think this can be fixed in the future?

**Comment by alsyundawy** [comment]
solved

clue, uninstall then fresh install

**Comment by Prajithp** [comment]
@KeithIMyers cPanel has to be fixed this issue as all api calls are failing when 2FA is enabled. If you don't mind could you please open a support ticket with cPanel? I will also check with them

**Comment by cunninghambr** [comment]
root@cpanel [~]# /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl
Use of bare << to mean <<"" is deprecated at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 127.
Use of bare << to mean <<"" is deprecated at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 135.
Global symbol "@subdomains" requires explicit package name at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 127.
Global symbol "@subdomains" requires explicit package name at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 127.
Global symbol "@subdomains" requires explicit package name at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 127.
Global symbol "@addondomains" requires explicit package name at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 127.
Global symbol "@alt_domains" requires explicit package name at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 127.
Global symbol "@subdomains" requires explicit package name at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 127.
Global symbol "@addondomains" requires explicit package name at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 127.
Global symbol "$alt_domain" requires explicit package name at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 135.
Global symbol "@alt_domains" requires explicit package name at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 135.
Global symbol "$main_domain" requires explicit package name at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 135.
Global symbol "$alt_domain" requires explicit package name at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 135.
Global symbol "$alt_domain" requires explicit package name at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 135.
Global symbol "$alt_domain" requires explicit package name at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 135.
Global symbol "$main_domain" requires explicit package name at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 135.
Global symbol "$alt_domain" requires explicit package name at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 135.
syntax error at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 144, near "HEAD
    return"
  (Might be a runaway multi-line << string starting on line 135)
/usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm has too many errors.
Compilation failed in require at /usr/local/cpanel/Cpanel/LetsEncrypt.pm line 13.
BEGIN failed--compilation aborted at /usr/local/cpanel/Cpanel/LetsEncrypt.pm line 13.
Compilation failed in require at /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl line 8.
BEGIN failed--compilation aborted at /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl line 8.

**Comment by Prajithp** [comment]
@cunninghambr , seems your perl is broken. Could please paste here the following commands output to investigate further.

``` bash
$> /usr/local/cpanel/3rdparty/bin/perl -e 'print $] . "\n"'
$> cat /usr/local/cpanel/version
$> head -n1 /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl
```

**Comment by cunninghambr** [comment]
@Prajithp 
root@cpanel [~]# /usr/local/cpanel/3rdparty/bin/perl -e 'print $] . "\n"'
5.014004
root@cpanel [~]# cat /usr/local/cpanel/version
11.54.0.21
root@cpanel [~]# head -n1 /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl
#!/usr/local/cpanel/3rdparty/bin/perl
root@cpanel [~]#

**Comment by JKetelaar** [comment]
I've got the same basic error; 500 error.
This is the result of calling `/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl`:

```
root@host [~]# /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl
Can't locate Protocol/ACME/Challenge.pm in @INC (you may need to install the Protocol::ACME::Challenge module) (@INC contains: /usr/local/cpanel/base/3rdparty/letsencrypt-cpanel-ui/lib/perl5 /usr/local/cpanel /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/cpanel_lib/x86_64-linux-64int /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/cpanel_lib /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/5.22.1/x86_64-linux-64int /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/5.22.1 /opt/cpanel/perl5/522/site_lib/x86_64-linux-64int /opt/cpanel/perl5/522/site_lib) at /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/5.22.1/parent.pm line 20.
BEGIN failed--compilation aborted at /usr/local/cpanel/Cpanel/LetsEncrypt/Challenge.pm line 6.
Compilation failed in require at /usr/local/cpanel/Cpanel/LetsEncrypt.pm line 10.
BEGIN failed--compilation aborted at /usr/local/cpanel/Cpanel/LetsEncrypt.pm line 10.
Compilation failed in require at /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl line 8.
BEGIN failed--compilation aborted at /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl line 8.
```

Any clue on this one?

**Comment by Prajithp** [comment]
@cunninghambr Could you please update your cPanel installation to latest release as I can see you are still on Perl version 5.14.

**Comment by Prajithp** [comment]
@JKetelaar Please uninstall and install again, that should fix your issue. Also, please provide the installation output if possible.

**Comment by cunninghambr** [comment]
@Prajithp  update 
/usr/local/cpanel/3rdparty/bin/perl -e 'print $] . "\n"'
5.022001
cat /usr/local/cpanel/version
11.56.0.8
head -n1 /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl
#!/usr/local/cpanel/3rdparty/bin/perl

and error persist

**Comment by JKetelaar** [comment]
Thanks a bunch @Prajithp, works like a charm.

**Comment by Prajithp** [comment]
@cunninghambr could u plz contact me on prajithpalakkuda@gmail.com? Just would like to discuss more about this issue.

**Comment by kushalraha** [comment]
Same error as @cunninghambr 

> root@serverxxx [/scripts]#  /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl
> Use of bare << to mean <<"" is deprecated at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 127.
> Use of bare << to mean <<"" is deprecated at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 127.
> Global symbol "@subdomains" requires explicit package name (did you forget to declare "my @subdomains"?) at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 128.
> Global symbol "@subdomains" requires explicit package name (did you forget to declare "my @subdomains"?) at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 130.
> Global symbol "@subdomains" requires explicit package name (did you forget to declare "my @subdomains"?) at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 131.
> Global symbol "@addondomains" requires explicit package name (did you forget to declare "my @addondomains"?) at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 133.
> Global symbol "@alt_domains" requires explicit package name (did you forget to declare "my @alt_domains"?) at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 134.
> Global symbol "@subdomains" requires explicit package name (did you forget to declare "my @subdomains"?) at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 134.
> Global symbol "@addondomains" requires explicit package name (did you forget to declare "my @addondomains"?) at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 134.
> Global symbol "$alt_domain" requires explicit package name (did you forget to declare "my $alt_domain"?) at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 136.
> Global symbol "@alt_domains" requires explicit package name (did you forget to declare "my @alt_domains"?) at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 136.
> Global symbol "$main_domain" requires explicit package name (did you forget to declare "my $main_domain"?) at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 137.
> Global symbol "$alt_domain" requires explicit package name (did you forget to declare "my $alt_domain"?) at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 137.
> Global symbol "$alt_domain" requires explicit package name (did you forget to declare "my $alt_domain"?) at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 138.
> Global symbol "$alt_domain" requires explicit package name (did you forget to declare "my $alt_domain"?) at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 138.
> Global symbol "$main_domain" requires explicit package name (did you forget to declare "my $main_domain"?) at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 138.
> Global symbol "$alt_domain" requires explicit package name (did you forget to declare "my $alt_domain"?) at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 139.
> syntax error at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 144, near "HEAD
>     return"
>   (Might be a runaway multi-line << string starting on line 136)
> /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm has too many errors.
> Compilation failed in require at /usr/local/cpanel/Cpanel/LetsEncrypt.pm line 13.
> BEGIN failed--compilation aborted at /usr/local/cpanel/Cpanel/LetsEncrypt.pm line 13.
> Compilation failed in require at /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl line 8.
> BEGIN failed--compilation aborted at /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl line 8.

Everything updated, reinstalled yet the same.

**Comment by jruston** [comment]
Same problem with 2 factor authentication turned on.

"500

No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 255 when it ended."

Works perfectly fine in cPanel, just not WHM. 2FA is enabled on both the cPanel and the WHM account.

[~/letsencrypt-cpanel]# /usr/local/cpanel/3rdparty/bin/perl -e 'print $] . "\n"'
5.022001
[~/letsencrypt-cpanel]# cat /usr/local/cpanel/version
11.56.0.14
head -n1 /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl
#!/usr/local/cpanel/3rdparty/bin/perl

[~/letsencrypt-cpanel]# /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl
Status: 400 Bad request
Content-Type: application/text; charset=ISO-8859-1

Access denied

**Comment by Prajithp** [comment]
@jrustonapps @kushalraha I'm not able to recreate this issue on any of my test boxes, so seems to be server configuration issue. Please contact me on prajithpalakkuda@gmail.com if you need any further assistance.

**Comment by rufftruffles** [comment]
@Prajithp I have the same issue, it happens when the LetsEncrypt WHM services certificate expires on its own and then you can not reinstall it.

Not an ARRAY reference at /usr/local/cpanel/base/3rdparty/letsencrypt-cpanel-ui/lib/perl5/Protocol/ACME.pm line 718.

**Comment by will-ashworth** [comment]
I hate to say it, but I just setup a new cPanel server today on CentOS 7, and having this issue.

```
Internal Server Error

500

No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 110 when it ended.
```

I'm using this plugin on other CentOS 6 boxes ...is there something wrong with compatibility on v7 that I should know about?

```
# /usr/local/cpanel/3rdparty/bin/perl -e 'print $] . "\n"'
5.022001
# cat /usr/local/cpanel/version
11.56.0.28
# head -n1 /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl
#!/usr/local/cpanel/3rdparty/bin/perl
```

**Comment by will-ashworth** [comment]
Additional Information:

```
# /usr/local/cpanel/3rdparty/bin/perl -v |grep version
This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-64int
```

**Comment by will-ashworth** [comment]
Actually, I think my firewall was getting in the way. Copied a config from another known-good server, and I think that's when it started working correctly.

**Comment by NabiKAZ** [comment]
I have the same issue.
I test on two server:

CENTOS 7.5 x64 kvm
Cpanel v74.0.4
Perl v5.026000
letsencrypt-cpanel Version Latest commit e3ea198  on Jan 30

====================
Web request for firstlly request: https://xxxxxxxxx:2087/cpsessxxxx/cgi/letsencrypt/letsencrypt.pl
```
Internal Server Error
500

No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): 
cpsrvd Server at xxxxxxxxx
```
===========================
Web request for try again request: https://xxxxxxxxx:2087/cpsessxxxx/cgi/letsencrypt/letsencrypt.pl
```
Internal Server Error
500

No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 72,057,594,037,927,935 when it ended. The process dumped a core file.
cpsrvd Server at xxxxxxx
```
=======================================
`# tailf /usr/local/cpanel/logs/error_log`
```
Server Error from 127.0.0.1: 403 Forbidden Access denied
Server Error from 127.0.0.1: 403 Forbidden Access denied at /usr/local/cpanel/3rdparty/perl/526/lib64/perl5/cpanel_lib/cPanel/PublicAPI.pm line 505.
[2018-08-11 16:05:54 +0430] info [whostmgrd] Internal Server Error: "GET /cpsessxxxxx/cgi/letsencrypt/letsencrypt.pl HTTP/1.1" 500 No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 72,057,594,037,927,935 when it ended. The process dumped a core file.
```
========================
`# /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl`
```
Status: 400 Bad request
Content-Type: application/text; charset=ISO-8859-1

Access denied
```
===================

The Two-Factor Authentication Security Policy is `Disabled`

===================
Try: uninstall then fresh install

`# ./install.sh`
```
Protocol::ACME is NOT installed
Installing Protocol::ACME
.....
.....
 Testing  perl modules we just installed
.....
Protocol::ACME is installed properly
.....
.....DONE
letsencrypt registered
info [install_plugin] Installing to paper_lantern
info [install_plugin] Installing letsencrypt in feature manager ...
info [install_plugin] Done
info [install_plugin] Running sprite_generator
info [install_plugin] Queueing task to update API spec files
Plugin installed ok
info [install_plugin] Installing to x3
warn [install_plugin] The specified theme [x3] does not exist.
Searching for themes that support the cpanel plugins system.............Done

Rebuild Complete
letsencrypt-cpanel-ui registered
Successfully installed letsencrypt manager
```
===================
`# /usr/local/cpanel/3rdparty/bin/perl -e 'print $] . "\n"'`
```
5.026000
```
===================
`# cat /usr/local/cpanel/version`
```
11.74.0.4
```
===================
`# head -n1 /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl`
```
#!/usr/local/cpanel/3rdparty/bin/perl
```
===================
`# /usr/local/cpanel/3rdparty/bin/perl -v |grep version`
```
This is perl 5, version 26, subversion 0 (v5.26.0) built for x86_64-linux-64int
```
===================

Firewall: csf and lfd have been `disabled`

===================
